language: python
python: 
- 3.5.2

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codeclimate-test-reporter

env:
  - FLASK_VERSION=1.0.2

script:
  pytest --cov=app/

after-success:
  - coveralls
